#博客名称
title: JustDoIt
#副标题
subtitle: 每天进步一点点
#简介
description: 记录生活点滴
#博客作者
author: Yabing Zhang
#博客语言
language: zh-CN
#时区
timezone:

#博客地址,与申请的GitHub一致
url: https://jim-bin.github.io/
root: /
#博客链接格式
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

default_category: uncategorized
category_map:
tag_map:

#日期格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss

#分页，每页文章数量
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#博客主题
theme: kiddochan

#发布设置
deploy:
  type: git
  repository: git@github.com:jim-bin/jim-bin.github.io.git
  branch: master 
